language: node_js
node_js:
- '11'
- '10'
- '8'
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: npm
  email:
    secure: S9XaSNK0kDZUz4tbH1GKtYdf7ox7GL8B+HHFXdZXCKbDQiRHIg4Ft/7RWjPq4+uCFX3ydJxx9f62kwdwo25J/Lx+zrq1YY73J8JdMqH/Pd4VlKbtppF+Rz9N9A9qYGw9xlnlX6/xrZ4YzxNh3DB6qfPkdH7wR6GBPlNVvKyW6OS2AyO9ICArNLqYs+qd9VdWh5VrIaHX3owtCr05hKlH7G07jHRGgJ4zxpX+KmEXuHaKEecpW+6214fCeo7aL2tFCNDE4kku8rLEmgudC2r8eUmnK1/lqns0e0ExvpyMXg+SF4SCewX4jbPfwm9swmCV6J0uQHhvI9MI9npbJfcD08IkxTl4vHnh1NF9A5wPIS25c3G7kx7ozjl9xAsoqUBHBrOWksME1XPOBns+SV8QXvJ6el9aQ/JuQDGmhgto78A3+/B61h5KyMOS/agw7j4mf6my4XCDlLtSutnznYHuTzpFFxp11dJefm7VKDyvrWaxgFUOsZoy0V/cSZE9tkL8SgI4iViuqvMjUP+HMaZu5WpR55hn5nk4nUPGdgN+ODPrJGHkkBkGV1EX41ArbI34XYoClEqezI6j2C3IhgelTDLevJlTZVJgvtZ4VvpALzYUkrdJE8oN7RHCLKE0XLmhRjPmsuGu3qOEbuCGyn0Ch0P5U5Wqb84IafujbRwrp0s=
  api_key:
    secure: QFDj0Uk8fmIF0txSiRE+I2xFqyxhoIwqePfNOXGmBuKcphy+k238YqPwY0eEtQ8T0vfTKRbRYmG6KERbHFS2BKa6TtIUEHyKkxD5B3TH0OKuZY17BzcPQ90mq7z/WXq9Nqj5dD7+k9QRwm/S7AWDK9q0+/McpC7Dhk7c7rqlzrQfBFgVkxFoY2w2+KFrOLk6GzBQ8ocJyEJq8MFuz+yecHpE37Q7SJRkPjny4o1P0sgGixDWXpUiY9pS2mOYRE7VEdNCCUiQPWo7lpE593Cc9K+W/NJq7D3An7vbzrPterwz+ohzfV35ShMOVm+qrfZ+LHLt0bc5X5mm6S43b9fWceXp1DbztxR1qJLWrY4naEdXmO7p7NAq5naddcbS3RPckxEOpI/fRzhsdqyBIP/RI1xKiPmD+ob/IOR/LUWyg63PTfRnP2Vi9mN9XP5Kzb2rM4qw019GzCeYaPo8/TuFyfTCmGez0Q2YT3T5ru1bY4xsT89ZzNH1qVoVYY5m6z12VP/vBk6qcTyJThsmjK5iCw4528e7lEQ+DV+gA47IbpneuhuXYJlMyn5mTGjrXkUU3zbzJjsnV9Wg2ScRNPRqbzVr/XcoEzawBLElbKTvfaqHC6krO5pxK8Mb2KGpJlrSkI/aJsEi/9Hs2IABn7HDU82z5WEGP+XgwH+17KHW23Q=
  on:
    tags: true
    repo: skiffek/node-scoreg
    branch: master
  skip_cleanup: true
